%% -*- mode: poly-latex-r


\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}

\usepackage[textmath,displaymath,showlabels]{preview}
\newenvironment{Rcode}[1][]{\begin{nopreview}}{\end{nopreview}}
\newenvironment{rcode}[1][]{\begin{nopreview}}{\end{nopreview}} 
\newcommand{\Sexpr}[1]{}

\PreviewEnvironment{align*}
\PreviewMacro*[{{}}]{\Sexpr}

\begin{document}



Some code:


\begin{Rcode}[echo=TRUE, background='#BAAAAA']
A <- list(x=1, y=3, z="Rnw")
A$x  #$
\end{Rcode}


\begin{rcode}

\end{rcode}


This file has the extension of \Sexpr{A[['z']]}.

\begin{rcode} 
r <- 9 + 888
r


\end{rcode}

Inline code:  Ax=\Sexpr{A$x} . 

Now some math:

\begin{align*}
 1+1&=2\\
 \alpha+\beta&=5
\end{align*}


Closing text.

\end{document}

