%% -*- mode: poly-latex+R -*-


\documentclass{article}
\usepackage{amsmath}

\usepackage[textmath,displaymath,showlabels]{preview}
\newenvironment{Rcode}[1][]{\begin{nopreview}}{\end{nopreview}}
\newcommand{\Sexpr}[1]{}

\PreviewEnvironment{align*}
\PreviewMacro*[{{}}]{\Sexpr}

\begin{document}


Some code:

\begin{Rcode}[]
A <- list(x=1, y=3, z="Rnw")
A$x  #$

\end{Rcode}


This file has the extension of \Sexpr{A[['z']]}.

\begin{Rcode}[]

\end{Rcode}

Inline code:  Ax=\Sexpr{A$x} .  %$

Now some math:

\begin{align*}
 1+1&=2\\
 \alpha+\beta&=5
\end{align*}

Closing text.

\end{document}

