%% -*- mode: poly-noweb+R -*-

\documentclass{article}
\usepackage{amsmath}

\usepackage[textmath,displaymath,showlabels]{preview}
\newenvironment{Rcode}[1][]{\begin{nopreview}}{\end{nopreview}}
\newcommand{\Sexpr}[1]{}

\PreviewEnvironment{align*}
\PreviewMacro*[{{}}]{\Sexpr}

\begin{document}


This file should compile with knit2pdf() without any modifications.  This is here to test support for legacy files (i.e., nothing is broken).

<<>>=
A <- list(x=3772, y="Rnw")
A
@

Inline code:  A=\Sexpr{A$x}. %$

Now some math:

\begin{align*}
 1+1&=2\\
 \alpha+\beta&=5
\end{align*}

Closing text.

\end{document}

